services:
  db:
    image: postgres:15
    container_name: issue_tracker_db
    environment:
      POSTGRES_USER: task-service
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: issue_tracker_app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: